<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Form task</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous"></head>
<body>
    <div class="container">
        <h1>Registracija į kursus</h1>
        <hr>
        <form action="profile.php" method="POST" enctype="multipart/form-data">
            <p>Vardas: 
                <input type="text" name="name" value="<?php echo isset($msg['error']) && isset($_POST['name']) ? $_POST['name'] : ''; ?>")>
            </p>
            <p>Pavardė: 
                <input type="text" name="lastname" value="<?php echo isset($msg['error']) && isset($_POST['lastname']) ? $_POST['lastname'] : ''; ?>")>
            </p>
            <p>Miestas: 
                <select name="city">
                    <?php foreach ($cities as $city): ?>
                    <option value="<?php echo $city; ?>"><?php echo $city; ?></option>
                    <?php endforeach; ?>
                </select>
            </p>
            <div>
                <h3>Programavimo kalba:</h3>
                <?php foreach ($langs as $lang): ?>
                <p><?php echo $lang; ?><input type="checkbox" name="language[]" value="<?php echo $lang; ?>"></p>
                <?php endforeach; ?>    
            </div>
            <h4>Papildoma informacija</h4>
            <textarea name="info" cols="40" rows="5" placeholder="Pvz. Turite C++ programavimo patirties"></textarea>
            <h4>Pridėti nuotrauką</h4>
            <p>
                <input class="form-control" type="file" name="photo"/>
            </p>
            <p>
                <button class="btn btn-success">Siųsti</button>
            </p>
        </form>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</html>